services:
  teatro-alalba:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pre-teatro-alalba
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pre-teatro-http.rule=Host(`pre-teatro.monghit.com`)"
      - "traefik.http.routers.pre-teatro-http.entrypoints=web"
      - "traefik.http.routers.pre-teatro-http.middlewares=https-redirect"
      - "traefik.http.routers.pre-teatro.rule=Host(`pre-teatro.monghit.com`)"
      - "traefik.http.routers.pre-teatro.entrypoints=websecure"
      - "traefik.http.routers.pre-teatro.tls=true"
      - "traefik.http.routers.pre-teatro.tls.certresolver=letsencrypt"
      - "traefik.http.services.pre-teatro.loadbalancer.server.port=80"
      - "traefik.http.routers.pre-teatro.middlewares=security-headers"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  traefik-net:
    external: true
